version: '3.8'
services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8090:8090"
    networks:
      - libmark-network

networks:
  libmark-network:
    external: true