spring.application.name=eureka-service
server.port=8090

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.register-with-eureka=false

#La visualización del registro de eureka debería quedar en false (no visible).
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

